from __future__ import annotations

from typing import Protocol

from domain.entities import Annotation, Book, ReadingProgress


class BookRepository(Protocol):
    def add(self, book: Book) -> Book: ...

    def get_by_id(self, book_id: int) -> Book | None: ...

    def get_by_path(self, file_path: str) -> Book | None: ...

    def list_all(self) -> list[Book]: ...

    def delete(self, book_id: int) -> None: ...


class AnnotationRepository(Protocol):
    def add(self, annotation: Annotation) -> Annotation: ...

    def list_by_book(self, book_id: int) -> list[Annotation]: ...

    def list_by_page(self, book_id: int, page_number: int) -> list[Annotation]: ...

    def delete(self, annotation_id: int) -> None: ...


class ReadingProgressRepository(Protocol):
    def get_by_book(self, book_id: int) -> ReadingProgress | None: ...

    def save(self, progress: ReadingProgress) -> None: ...
